### ISSUE TITLE
Black frame generated after server epochs

### ISSUE THREAD

**Issue by miaojiang1987** [liruilong940607/glcic.pytorch#1]
Dear Ruilong Li,

Thank you for implementing this. It is excellent work to reproduce the training code with python. 

However, I found two issues after I trained the model several epochs. I trained with my own data with initial model completionnet_places2.t7. On the first of the epochs, it would do an OK job, however, there is a gray frame covered.

This image is generated from my own data set. And you can see a grey box is covered on top of that.
![image](https://user-images.githubusercontent.com/17423790/42566853-d72a7216-8542-11e8-969b-bbf1c8222496.png)

After several epochs, the completion part is totally black. Could you explain why? Is it because overfiting?

Here is an artifact generated after 10 epochs.  You can see a black box in the image. This is generated from the Places dataset. 
![image](https://user-images.githubusercontent.com/17423790/42566932-2bf1882a-8543-11e8-8daa-ed1e2589261b.png)

Again, thank you for your work and I really appreciate your hard work. Many thanks to your reply.

Best,
Miao Jiang

**Comment by liruilong940607** [comment]
Thank you for watching.

This repo is an old version with some bugs. **I've just updated this repo to the newest**. But I'm sorry to say I don't think I successfully reproduce the author's result, although the code seems fine now.

1. The result of pretrained model seems ok. The author of this paper used a blend postprocess to fade this edge problem. You can find the codes of this part in `blend.py`

2. I also just try this on my own dataset. Here are some good & bad results. I think the good results prove the codes are ok now, but the bad results indicate this repo need improvement.

![image](https://user-images.githubusercontent.com/10151885/42624622-61341f38-85f8-11e8-8a56-e168fe65dc7d.png)
![image](https://user-images.githubusercontent.com/10151885/42624725-b175aa3e-85f8-11e8-9585-737a78b59a24.png)

**Comment by miaojiang1987** [comment]
Thanks a lot! Ruilong! It is really nice of you for helping me with the issue. Please ignore my email sent to you. I will test it again.
